trigger:
- master

jobs:
- job: Test01
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      filePath: 'build.ps1'
      arguments: 'Test --partition-Test 1/2'
- job: Test02
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      filePath: 'build.ps1'
      arguments: 'Test --partition-Test 2/2'
- job: Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo After all partitions
