trigger:
- master

jobs:
- job: Test
  strategy:
    parallel: 2
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: PowerShell@2
    displayName: 'Build'
    inputs:
      filePath: 'build.ps1'
      arguments: 'Test --partition-Test $(System.JobPositionInPhase)/$(System.TotalJobsInPhase)'
- job: Package
  dependsOn:
  - Test
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo After all partitions
